# Generated by Django 5.1.1 on 2025-10-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='task',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
