# Generated by Django 6.0.5 on 2026-06-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_user_organization_remove_task_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Project Manager'), ('worker', 'Engineer')], max_length=10),
        ),
    ]
