# Generated by Django 5.1.15 on 2026-07-05 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_task_priority_taskattachment_taskcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="pay_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="user",
            name="monthly_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="user",
            name="pay_type",
            field=models.CharField(
                choices=[("monthly", "Monthly salary"), ("per_task", "Paid per task")],
                default="monthly",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="task_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Default pay for each approved task (used when a task has no explicit amount).",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly salary"),
                            ("per_task", "Per task"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        help_text="e.g. a month, sprint or free text.",
                        max_length=40,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("task_count", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engineer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.payment",
            ),
        ),
    ]
