# Generated by Django 5.1.15 on 2026-07-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_task_approved_task_approved_at_task_pay_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="progress",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
