# Generated by Django 5.1.15 on 2026-07-05 09:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_subtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="task",
            name="due_time",
            field=models.TimeField(
                blank=True, help_text="Optional time of day the task is due.", null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="estimated_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name="user",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Pay per hour of logged time (for per-hour engineers).",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="basis",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly salary"),
                    ("per_task", "Per task"),
                    ("hourly", "Per hour"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="pay_type",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly salary"),
                    ("per_task", "Paid per task"),
                    ("hourly", "Paid per hour"),
                ],
                default="monthly",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="TimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours", models.DecimalField(decimal_places=2, max_digits=6)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "work_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="time_logs",
                        to="tasks.payment",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-work_date", "-id"],
            },
        ),
    ]
