# Generated by Django 5.1.15 on 2026-07-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_payment_hours_task_due_time_task_estimated_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="late_penalty_percent",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Percent of pay deducted if finished after the deadline (0 = none).",
            ),
        ),
    ]
