# Generated by Django 5.1.15 on 2026-07-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_task_late_penalty_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="fine",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="task",
            name="fine_settled",
            field=models.BooleanField(default=False),
        ),
    ]
