# Generated by Django 5.1.15 on 2026-07-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_payment_fine_task_fine_settled"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="destination",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="reference",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="user",
            name="bank_account",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="user",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="mpesa_phone",
            field=models.CharField(
                blank=True, help_text="e.g. 0712 345678", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="payout_method",
            field=models.CharField(
                choices=[("mpesa", "M-Pesa"), ("bank", "Bank transfer")],
                default="mpesa",
                max_length=10,
            ),
        ),
    ]
