# Generated by Django 5.1.15 on 2026-07-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0013_payment_destination_payment_method_payment_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="provider_ref",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(default="simulated", max_length=10),
        ),
    ]
